// <auto-generated />
using System;
using MeteoriteAPI.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeteoriteAPI.Domain.Migrations.Migrations
{
    [DbContext(typeof(MeteoritesContext))]
    partial class MeteoritesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeteoriteAPI.Domain.Models.Meteorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fall")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fall");

                    b.Property<decimal?>("GeolocationCoordinatesLat")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)")
                        .HasColumnName("coordinates_lat");

                    b.Property<decimal?>("GeolocationCoordinatesLong")
                        .HasPrecision(18, 5)
                        .HasColumnType("decimal(18,5)")
                        .HasColumnName("coordinates_long");

                    b.Property<string>("GeolocationType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<decimal?>("Mass")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("mass");

                    b.Property<int>("MeteoriteId")
                        .HasColumnType("int")
                        .HasColumnName("meteorite_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.Property<string>("NameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nametype");

                    b.Property<string>("RecClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("recclass");

                    b.Property<decimal?>("RecLat")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("reclat");

                    b.Property<decimal?>("RecLong")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)")
                        .HasColumnName("reclong");

                    b.Property<int?>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("RecClass");

                    b.ToTable("meteorites", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
